import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import Providers from '@/components/providers'
import { Geist, Geist_Mono } from 'next/font/google'

import Header from '@/components/header'
import Footer from '@/components/footer'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body
          className={cn(
            'flex min-h-screen flex-col font-sans antialiased',
            geistSans.variable,
            geistMono.variable
          )}
        >
          <Providers>
            <Header />
            <main className='flex-1'>{children}</main>
            <Footer />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
